import {
  CASUALTY_CONDITIONS,
  CLUSTERS,
  DAMAGE_CONDITION,
  EVENT_STATUSES,
  LOCATIONS,
  POSITIONS,
  UNITS,
  USER_TYPES,
} from '@/lib';
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '@prisma/client';
import 'dotenv/config';

const adapter = new PrismaPg({ connectionString: process.env.SHADOW_DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

// ─── Quarter → approximate NSED drill dates ───────────────
const QUARTER_DATES: Record<string, { started_at: Date; ended_at: Date }> = {
  'Q1 2025': {
    started_at: new Date('2025-03-13T14:00:00+08:00'),
    ended_at: new Date('2025-03-13T15:00:00+08:00'),
  },
  'Q2 2025': {
    started_at: new Date('2025-06-19T09:00:00+08:00'),
    ended_at: new Date('2025-06-19T10:00:00+08:00'),
  },
  'Q3 2025': {
    started_at: new Date('2025-09-11T16:00:00+08:00'),
    ended_at: new Date('2025-09-11T17:00:00+08:00'),
  },
  'Q4 2025': {
    started_at: new Date('2025-11-06T09:00:00+08:00'),
    ended_at: new Date('2025-11-06T10:00:00+08:00'),
  },
  'Q1 2026': {
    started_at: new Date('2026-03-12T15:30:00+08:00'),
    ended_at: new Date('2026-03-12T16:30:00+08:00'),
  },
  'Q2 2026': {
    started_at: new Date('2026-06-18T09:00:00+08:00'),
    ended_at: new Date('2026-06-18T10:00:00+08:00'),
  },
  'Q3 2026': {
    started_at: new Date('2026-09-10T14:00:00+08:00'),
    ended_at: new Date('2026-09-10T15:00:00+08:00'),
  },
  'Q4 2026': {
    started_at: new Date('2026-11-05T09:00:00+08:00'),
    ended_at: new Date('2026-11-05T10:00:00+08:00'),
  },
};

// ─── Bystander incident types ─────────────────────────────
const BYSTANDER_INCIDENT_TYPES = [
  'Earthquake',
  'Fire',
  'Flooding',
  'Medical Emergency',
  'Chemical Hazard',
  'Structural Collapse',
  'Power Outage',
  'Security Threat',
  'Missing Person',
  'Other',
];

// ─── Historical report data from Monday.com export ───────
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const REPORT_DATA: any[] = [
  {
    quarter: 'Q1 2025',
    cluster: 'Pedro Gil',
    unit: 'College of Nursing',
    faculty_members: 17,
    admin_members: 14,
    reps_members: 0,
    ra_members: 0,
    students: 115,
    philcare_staff: 4,
    security_personnel: 1,
    construction_workers: 0,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 1,
    guests: 5,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2025-01-23T12:33:00+08:00',
  },
  {
    quarter: 'Q1 2025',
    cluster: 'Pedro Gil',
    unit: 'National Institutes of Health',
    faculty_members: 0,
    admin_members: 12,
    reps_members: 0,
    ra_members: 0,
    students: 0,
    philcare_staff: 0,
    security_personnel: 0,
    construction_workers: 0,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 2,
    casualties_count: 0,
    timestamp: '2025-01-23T14:05:00+08:00',
  },
  {
    quarter: 'Q1 2025',
    cluster: 'Pedro Gil',
    unit: 'College of Pharmacy',
    faculty_members: 12,
    admin_members: 16,
    reps_members: 0,
    ra_members: 4,
    students: 85,
    philcare_staff: 5,
    security_personnel: 2,
    construction_workers: 7,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 4,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2025-01-23T14:09:00+08:00',
  },
  {
    quarter: 'Q1 2025',
    cluster: 'Pedro Gil',
    unit: 'College of Allied Medical Professions',
    faculty_members: 21,
    admin_members: 13,
    reps_members: 3,
    ra_members: 1,
    students: 122,
    philcare_staff: 3,
    security_personnel: 1,
    construction_workers: 0,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2025-01-23T14:10:00+08:00',
  },
  {
    quarter: 'Q1 2025',
    cluster: 'Pedro Gil',
    unit: 'College of Dentistry',
    faculty_members: 23,
    admin_members: 4,
    reps_members: 1,
    ra_members: 0,
    students: 118,
    philcare_staff: 6,
    security_personnel: 3,
    construction_workers: 1,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 22,
    guests: 66,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2025-01-23T14:14:00+08:00',
  },
  {
    quarter: 'Q1 2025',
    cluster: 'Pedro Gil',
    unit: 'College of Public Health',
    faculty_members: 9,
    admin_members: 32,
    reps_members: 16,
    ra_members: 2,
    students: 38,
    philcare_staff: 8,
    security_personnel: 2,
    construction_workers: 2,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 3,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2025-01-23T14:16:00+08:00',
  },
  {
    quarter: 'Q1 2025',
    cluster: 'Pedro Gil',
    unit: 'College of Nursing',
    faculty_members: 3,
    admin_members: 6,
    reps_members: 1,
    ra_members: 2,
    students: 114,
    philcare_staff: 4,
    security_personnel: 2,
    construction_workers: 0,
    tenants: 15,
    health_workers: 0,
    non_academic_staff: 2,
    guests: 1,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2025-01-23T14:29:00+08:00',
  },
  {
    quarter: 'Q1 2025',
    cluster: 'Padre Faura',
    unit: 'College of Arts and Sciences',
    faculty_members: 23,
    admin_members: 29,
    reps_members: 0,
    ra_members: 4,
    students: 429,
    philcare_staff: 17,
    security_personnel: 8,
    construction_workers: 27,
    tenants: 5,
    health_workers: 0,
    non_academic_staff: 27,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2025-01-23T14:08:00+08:00',
  },
  {
    quarter: 'Q1 2025',
    cluster: 'Padre Faura',
    unit: 'Joaquin Gonzales Building',
    faculty_members: 0,
    admin_members: 5,
    reps_members: 1,
    ra_members: 0,
    students: 0,
    philcare_staff: 0,
    security_personnel: 0,
    construction_workers: 0,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2025-01-23T14:31:00+08:00',
  },
  {
    quarter: 'Q1 2025',
    cluster: 'Taft',
    unit: 'Central Administration (CAD)',
    faculty_members: 0,
    admin_members: 0,
    reps_members: 0,
    ra_members: 0,
    students: 0,
    philcare_staff: 0,
    security_personnel: 2,
    construction_workers: 0,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 3,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2025-01-23T13:13:00+08:00',
  },
  {
    quarter: 'Q1 2025',
    cluster: 'Taft',
    unit: 'Central Administration (CAD)',
    faculty_members: 0,
    admin_members: 3,
    reps_members: 2,
    ra_members: 2,
    students: 0,
    philcare_staff: 1,
    security_personnel: 0,
    construction_workers: 0,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 1,
    timestamp: '2025-01-23T14:16:00+08:00',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'PGH',
    unit: 'Zone 11',
    faculty_members: 0,
    admin_members: 12,
    reps_members: 0,
    ra_members: 0,
    students: 0,
    philcare_staff: 0,
    security_personnel: 0,
    construction_workers: 0,
    tenants: 2,
    health_workers: 12,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2025-04-24T10:19:00+08:00',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'PGH',
    unit: 'Zone 9',
    faculty_members: 0,
    admin_members: 0,
    reps_members: 0,
    ra_members: 0,
    students: 0,
    philcare_staff: 0,
    security_personnel: 0,
    construction_workers: 0,
    tenants: 40,
    health_workers: 33,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 2,
    timestamp: '2025-04-24T10:21:00+08:00',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'PGH',
    unit: 'Zone 1',
    faculty_members: 246,
    admin_members: 246,
    reps_members: 246,
    ra_members: 246,
    students: 246,
    philcare_staff: 246,
    security_personnel: 246,
    construction_workers: 246,
    tenants: 246,
    health_workers: 246,
    non_academic_staff: 246,
    guests: 246,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2025-04-24T08:54:00+08:00',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'PGH',
    unit: 'Zone 2',
    faculty_members: 85,
    admin_members: 85,
    reps_members: 85,
    ra_members: 85,
    students: 85,
    philcare_staff: 85,
    security_personnel: 85,
    construction_workers: 85,
    tenants: 85,
    health_workers: 85,
    non_academic_staff: 85,
    guests: 85,
    missing_count: 5,
    casualties_count: 0,
    timestamp: '2025-04-24T08:57:00+08:00',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'PGH',
    unit: 'Zone 3',
    faculty_members: 136,
    admin_members: 136,
    reps_members: 136,
    ra_members: 136,
    students: 136,
    philcare_staff: 136,
    security_personnel: 136,
    construction_workers: 136,
    tenants: 136,
    health_workers: 136,
    non_academic_staff: 136,
    guests: 136,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2025-04-24T08:58:00+08:00',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'PGH',
    unit: 'Zone 4',
    faculty_members: 590,
    admin_members: 590,
    reps_members: 590,
    ra_members: 590,
    students: 590,
    philcare_staff: 590,
    security_personnel: 590,
    construction_workers: 590,
    tenants: 590,
    health_workers: 590,
    non_academic_staff: 590,
    guests: 590,
    missing_count: 17,
    casualties_count: 550,
    timestamp: '2025-04-24T09:06:00+08:00',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'PGH',
    unit: 'Zone 5',
    faculty_members: 73,
    admin_members: 73,
    reps_members: 73,
    ra_members: 73,
    students: 73,
    philcare_staff: 73,
    security_personnel: 73,
    construction_workers: 73,
    tenants: 73,
    health_workers: 73,
    non_academic_staff: 73,
    guests: 73,
    missing_count: 0,
    casualties_count: 500,
    timestamp: '2025-04-24T09:09:00+08:00',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'PGH',
    unit: 'Zone 5',
    faculty_members: 73,
    admin_members: 73,
    reps_members: 73,
    ra_members: 73,
    students: 73,
    philcare_staff: 73,
    security_personnel: 73,
    construction_workers: 73,
    tenants: 73,
    health_workers: 73,
    non_academic_staff: 73,
    guests: 73,
    missing_count: 0,
    casualties_count: 500,
    timestamp: '2025-04-24T09:14:00+08:00',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'PGH',
    unit: 'Zone 6',
    faculty_members: 50,
    admin_members: 50,
    reps_members: 50,
    ra_members: 50,
    students: 50,
    philcare_staff: 50,
    security_personnel: 50,
    construction_workers: 50,
    tenants: 50,
    health_workers: 50,
    non_academic_staff: 50,
    guests: 50,
    missing_count: 0,
    casualties_count: 43,
    timestamp: '2025-04-24T09:15:00+08:00',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'PGH',
    unit: 'Zone 7',
    faculty_members: 56,
    admin_members: 56,
    reps_members: 56,
    ra_members: 56,
    students: 56,
    philcare_staff: 56,
    security_personnel: 56,
    construction_workers: 56,
    tenants: 56,
    health_workers: 56,
    non_academic_staff: 56,
    guests: 56,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2025-04-24T09:16:00+08:00',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'PGH',
    unit: 'Zone 8',
    faculty_members: 150,
    admin_members: 150,
    reps_members: 150,
    ra_members: 150,
    students: 150,
    philcare_staff: 150,
    security_personnel: 150,
    construction_workers: 150,
    tenants: 150,
    health_workers: 150,
    non_academic_staff: 150,
    guests: 150,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2025-04-24T09:18:00+08:00',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'PGH',
    unit: 'Zone 9',
    faculty_members: 69,
    admin_members: 69,
    reps_members: 69,
    ra_members: 69,
    students: 69,
    philcare_staff: 69,
    security_personnel: 69,
    construction_workers: 69,
    tenants: 69,
    health_workers: 69,
    non_academic_staff: 69,
    guests: 69,
    missing_count: 0,
    casualties_count: 2,
    timestamp: '2025-04-24T09:20:00+08:00',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'PGH',
    unit: 'Zone 10',
    faculty_members: 71,
    admin_members: 71,
    reps_members: 71,
    ra_members: 71,
    students: 71,
    philcare_staff: 71,
    security_personnel: 71,
    construction_workers: 71,
    tenants: 71,
    health_workers: 71,
    non_academic_staff: 71,
    guests: 71,
    missing_count: 0,
    casualties_count: 2234,
    timestamp: '2025-04-24T09:23:00+08:00',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'PGH',
    unit: 'Zone 11',
    faculty_members: 12,
    admin_members: 12,
    reps_members: 12,
    ra_members: 12,
    students: 12,
    philcare_staff: 12,
    security_personnel: 12,
    construction_workers: 12,
    tenants: 12,
    health_workers: 12,
    non_academic_staff: 12,
    guests: 12,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2025-04-24T09:24:00+08:00',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'PGH',
    unit: 'Zone 12',
    faculty_members: 172,
    admin_members: 172,
    reps_members: 172,
    ra_members: 172,
    students: 172,
    philcare_staff: 172,
    security_personnel: 172,
    construction_workers: 172,
    tenants: 172,
    health_workers: 172,
    non_academic_staff: 172,
    guests: 172,
    missing_count: 0,
    casualties_count: 5,
    timestamp: '2025-04-24T09:25:00+08:00',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'Pedro Gil',
    unit: 'College of Nursing',
    faculty_members: 4,
    admin_members: 13,
    reps_members: 4,
    ra_members: 0,
    students: 1,
    philcare_staff: 5,
    security_personnel: 1,
    construction_workers: 0,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2025-04-24T09:06:00+08:00',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'Pedro Gil',
    unit: 'UP Manila Phi House Dormitory',
    faculty_members: 0,
    admin_members: 1,
    reps_members: 0,
    ra_members: 0,
    students: 0,
    philcare_staff: 1,
    security_personnel: 1,
    construction_workers: 0,
    tenants: 8,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 7,
    casualties_count: 2,
    timestamp: '2025-04-24T09:54:00+08:00',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'Pedro Gil',
    unit: 'College of Public Health',
    faculty_members: 5,
    admin_members: 32,
    reps_members: 8,
    ra_members: 5,
    students: 1,
    philcare_staff: 8,
    security_personnel: 3,
    construction_workers: 0,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 35,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2025-04-24T09:12:00+08:00',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'Pedro Gil',
    unit: 'UP Manila Dorm',
    faculty_members: 0,
    admin_members: 2,
    reps_members: 0,
    ra_members: 0,
    students: 0,
    philcare_staff: 1,
    security_personnel: 1,
    construction_workers: 0,
    tenants: 26,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 9,
    casualties_count: 2,
    timestamp: '2025-04-24T09:58:00+08:00',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'Pedro Gil',
    unit: 'College of Medicine',
    faculty_members: 20,
    admin_members: 69,
    reps_members: 7,
    ra_members: 4,
    students: 47,
    philcare_staff: 21,
    security_personnel: 8,
    construction_workers: 16,
    tenants: 0,
    health_workers: 2,
    non_academic_staff: 0,
    guests: 5,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2025-04-24T09:17:00+08:00',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'Pedro Gil',
    unit: 'National Institutes of Health',
    faculty_members: 0,
    admin_members: 10,
    reps_members: 0,
    ra_members: 0,
    students: 0,
    philcare_staff: 0,
    security_personnel: 0,
    construction_workers: 0,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2025-04-24T09:08:00+08:00',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'Padre Faura',
    unit: 'Joaquin Gonzales Building',
    faculty_members: 0,
    admin_members: 5,
    reps_members: 1,
    ra_members: 0,
    students: 0,
    philcare_staff: 2,
    security_personnel: 0,
    construction_workers: 0,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2025-04-24T09:42:00+08:00',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'Taft',
    unit: 'Central Administration (CAD)',
    faculty_members: 4,
    admin_members: 54,
    reps_members: 2,
    ra_members: 1,
    students: 0,
    philcare_staff: 7,
    security_personnel: 2,
    construction_workers: 0,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 46,
    guests: 0,
    missing_count: 0,
    casualties_count: 8,
    timestamp: '2025-04-24T10:33:00+08:00',
  },
  {
    quarter: 'Q3 2025',
    cluster: 'Pedro Gil',
    unit: 'UP Manila Dorm',
    faculty_members: 0,
    admin_members: 3,
    reps_members: 0,
    ra_members: 0,
    students: 0,
    philcare_staff: 1,
    security_personnel: 1,
    construction_workers: 0,
    tenants: 36,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 7,
    casualties_count: 0,
    timestamp: '2025-07-24T09:34:00+08:00',
  },
  {
    quarter: 'Q3 2025',
    cluster: 'Pedro Gil',
    unit: 'National Institutes of Health',
    faculty_members: 0,
    admin_members: 13,
    reps_members: 0,
    ra_members: 0,
    students: 0,
    philcare_staff: 0,
    security_personnel: 0,
    construction_workers: 0,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2025-07-24T16:05:00+08:00',
  },
  {
    quarter: 'Q3 2025',
    cluster: 'Pedro Gil',
    unit: 'College of Allied Medical Professions',
    faculty_members: 14,
    admin_members: 14,
    reps_members: 1,
    ra_members: 0,
    students: 92,
    philcare_staff: 2,
    security_personnel: 1,
    construction_workers: 9,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2025-07-24T16:09:00+08:00',
  },
  {
    quarter: 'Q3 2025',
    cluster: 'Pedro Gil',
    unit: 'College of Dentistry',
    faculty_members: 22,
    admin_members: 20,
    reps_members: 0,
    ra_members: 0,
    students: 212,
    philcare_staff: 7,
    security_personnel: 3,
    construction_workers: 2,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 4,
    guests: 12,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2025-07-24T16:14:00+08:00',
  },
  {
    quarter: 'Q3 2025',
    cluster: 'Pedro Gil',
    unit: 'National Institutes of Health',
    faculty_members: 0,
    admin_members: 60,
    reps_members: 6,
    ra_members: 0,
    students: 0,
    philcare_staff: 3,
    security_personnel: 3,
    construction_workers: 0,
    tenants: 0,
    health_workers: 1,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2025-07-24T16:16:00+08:00',
  },
  {
    quarter: 'Q3 2025',
    cluster: 'Pedro Gil',
    unit: 'College of Nursing',
    faculty_members: 11,
    admin_members: 13,
    reps_members: 3,
    ra_members: 0,
    students: 65,
    philcare_staff: 5,
    security_personnel: 1,
    construction_workers: 3,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 1,
    guests: 1,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2025-07-24T16:22:00+08:00',
  },
  {
    quarter: 'Q3 2025',
    cluster: 'Pedro Gil',
    unit: 'College of Medicine',
    faculty_members: 16,
    admin_members: 66,
    reps_members: 2,
    ra_members: 14,
    students: 118,
    philcare_staff: 18,
    security_personnel: 11,
    construction_workers: 19,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2025-07-24T16:23:00+08:00',
  },
  {
    quarter: 'Q3 2025',
    cluster: 'Pedro Gil',
    unit: 'UP Manila Phi House Dormitory',
    faculty_members: 0,
    admin_members: 2,
    reps_members: 0,
    ra_members: 0,
    students: 0,
    philcare_staff: 0,
    security_personnel: 1,
    construction_workers: 0,
    tenants: 22,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 1,
    timestamp: '2025-07-24T16:28:00+08:00',
  },
  {
    quarter: 'Q3 2025',
    cluster: 'Pedro Gil',
    unit: 'UP Manila Dorm',
    faculty_members: 0,
    admin_members: 2,
    reps_members: 0,
    ra_members: 0,
    students: 0,
    philcare_staff: 0,
    security_personnel: 1,
    construction_workers: 0,
    tenants: 34,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 1,
    missing_count: 4,
    casualties_count: 1,
    timestamp: '2025-07-24T16:52:00+08:00',
  },
  {
    quarter: 'Q3 2025',
    cluster: 'Padre Faura',
    unit: 'Joaquin Gonzales Building',
    faculty_members: 0,
    admin_members: 5,
    reps_members: 1,
    ra_members: 0,
    students: 0,
    philcare_staff: 1,
    security_personnel: 0,
    construction_workers: 0,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2025-07-24T16:04:00+08:00',
  },
  {
    quarter: 'Q3 2025',
    cluster: 'Padre Faura',
    unit: 'Campus Planning, Development, and Management Office',
    faculty_members: 0,
    admin_members: 25,
    reps_members: 0,
    ra_members: 0,
    students: 11,
    philcare_staff: 1,
    security_personnel: 1,
    construction_workers: 0,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 4,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2025-07-24T16:18:00+08:00',
  },
  {
    quarter: 'Q4 2025',
    cluster: 'Pedro Gil',
    unit: 'College of Medicine',
    faculty_members: 23,
    admin_members: 77,
    reps_members: 1,
    ra_members: 8,
    students: 408,
    philcare_staff: 24,
    security_personnel: 10,
    construction_workers: 21,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 1,
    guests: 21,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2025-10-23T09:15:00+08:00',
  },
  {
    quarter: 'Q4 2025',
    cluster: 'Pedro Gil',
    unit: 'UP Manila Phi House Dormitory',
    faculty_members: 0,
    admin_members: 1,
    reps_members: 0,
    ra_members: 0,
    students: 0,
    philcare_staff: 1,
    security_personnel: 1,
    construction_workers: 0,
    tenants: 21,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 11,
    casualties_count: 0,
    timestamp: '2025-10-23T10:06:00+08:00',
  },
  {
    quarter: 'Q4 2025',
    cluster: 'Pedro Gil',
    unit: 'College of Dentistry',
    faculty_members: 20,
    admin_members: 24,
    reps_members: 0,
    ra_members: 0,
    students: 131,
    philcare_staff: 7,
    security_personnel: 3,
    construction_workers: 0,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 24,
    guests: 38,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2025-10-23T09:04:00+08:00',
  },
  {
    quarter: 'Q4 2025',
    cluster: 'Pedro Gil',
    unit: 'College of Nursing',
    faculty_members: 5,
    admin_members: 12,
    reps_members: 4,
    ra_members: 0,
    students: 70,
    philcare_staff: 5,
    security_personnel: 1,
    construction_workers: 0,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 1,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2025-10-23T09:09:00+08:00',
  },
  {
    quarter: 'Q4 2025',
    cluster: 'Pedro Gil',
    unit: 'College of Pharmacy',
    faculty_members: 7,
    admin_members: 17,
    reps_members: 0,
    ra_members: 0,
    students: 73,
    philcare_staff: 4,
    security_personnel: 2,
    construction_workers: 7,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2025-10-23T09:10:00+08:00',
  },
  {
    quarter: 'Q4 2025',
    cluster: 'Pedro Gil',
    unit: 'National Institutes of Health',
    faculty_members: 5,
    admin_members: 76,
    reps_members: 7,
    ra_members: 3,
    students: 0,
    philcare_staff: 5,
    security_personnel: 2,
    construction_workers: 0,
    tenants: 0,
    health_workers: 2,
    non_academic_staff: 0,
    guests: 7,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2025-10-23T09:17:00+08:00',
  },
  {
    quarter: 'Q4 2025',
    cluster: 'Pedro Gil',
    unit: 'National Institutes of Health',
    faculty_members: 0,
    admin_members: 13,
    reps_members: 0,
    ra_members: 0,
    students: 0,
    philcare_staff: 0,
    security_personnel: 0,
    construction_workers: 0,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 1,
    casualties_count: 0,
    timestamp: '2025-10-23T09:27:00+08:00',
  },
  {
    quarter: 'Q4 2025',
    cluster: 'Pedro Gil',
    unit: 'College of Allied Medical Professions',
    faculty_members: 7,
    admin_members: 15,
    reps_members: 3,
    ra_members: 0,
    students: 142,
    philcare_staff: 2,
    security_personnel: 1,
    construction_workers: 11,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2025-10-23T09:11:00+08:00',
  },
  {
    quarter: 'Q4 2025',
    cluster: 'Padre Faura',
    unit: 'Campus Planning, Development, and Management Office',
    faculty_members: 0,
    admin_members: 25,
    reps_members: 0,
    ra_members: 0,
    students: 10,
    philcare_staff: 1,
    security_personnel: 1,
    construction_workers: 4,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2025-10-23T09:20:00+08:00',
  },
  {
    quarter: 'Q4 2025',
    cluster: 'Padre Faura',
    unit: 'College of Arts and Sciences',
    faculty_members: 0,
    admin_members: 0,
    reps_members: 0,
    ra_members: 2,
    students: 630,
    philcare_staff: 23,
    security_personnel: 8,
    construction_workers: 33,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 31,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2025-10-23T09:11:00+08:00',
  },
  {
    quarter: 'Q4 2025',
    cluster: 'Padre Faura',
    unit: 'Joaquin Gonzales Building',
    faculty_members: 0,
    admin_members: 5,
    reps_members: 2,
    ra_members: 0,
    students: 0,
    philcare_staff: 1,
    security_personnel: 0,
    construction_workers: 0,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2025-10-23T09:09:00+08:00',
  },
  {
    quarter: 'Q1 2026',
    cluster: 'Pedro Gil',
    unit: 'UP Manila Dorm',
    faculty_members: 0,
    admin_members: 2,
    reps_members: 0,
    ra_members: 0,
    students: 0,
    philcare_staff: 1,
    security_personnel: 1,
    construction_workers: 3,
    tenants: 21,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 4,
    casualties_count: 0,
    timestamp: '2026-01-22T16:00:00+08:00',
  },
  {
    quarter: 'Q1 2026',
    cluster: 'Pedro Gil',
    unit: 'UP Manila Phi House Dormitory',
    faculty_members: 0,
    admin_members: 0,
    reps_members: 0,
    ra_members: 0,
    students: 0,
    philcare_staff: 1,
    security_personnel: 1,
    construction_workers: 0,
    tenants: 13,
    health_workers: 0,
    non_academic_staff: 2,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2026-01-22T16:02:00+08:00',
  },
  {
    quarter: 'Q1 2026',
    cluster: 'Pedro Gil',
    unit: 'College of Nursing',
    faculty_members: 5,
    admin_members: 12,
    reps_members: 3,
    ra_members: 0,
    students: 106,
    philcare_staff: 4,
    security_personnel: 1,
    construction_workers: 0,
    tenants: 2,
    health_workers: 0,
    non_academic_staff: 1,
    guests: 2,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2026-01-22T15:51:00+08:00',
  },
  {
    quarter: 'Q1 2026',
    cluster: 'Pedro Gil',
    unit: 'College of Dentistry',
    faculty_members: 37,
    admin_members: 7,
    reps_members: 1,
    ra_members: 0,
    students: 107,
    philcare_staff: 7,
    security_personnel: 3,
    construction_workers: 5,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 20,
    guests: 63,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2026-01-22T15:44:00+08:00',
  },
  {
    quarter: 'Q1 2026',
    cluster: 'Pedro Gil',
    unit: 'College of Allied Medical Professions',
    faculty_members: 12,
    admin_members: 11,
    reps_members: 3,
    ra_members: 0,
    students: 87,
    philcare_staff: 3,
    security_personnel: 1,
    construction_workers: 0,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 4,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2026-01-22T15:42:00+08:00',
  },
  {
    quarter: 'Q1 2026',
    cluster: 'Pedro Gil',
    unit: 'National Institutes of Health',
    faculty_members: 3,
    admin_members: 161,
    reps_members: 28,
    ra_members: 15,
    students: 0,
    philcare_staff: 5,
    security_personnel: 2,
    construction_workers: 0,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 1,
    casualties_count: 0,
    timestamp: '2026-01-22T15:41:00+08:00',
  },
  {
    quarter: 'Q1 2026',
    cluster: 'Pedro Gil',
    unit: 'College of Pharmacy',
    faculty_members: 16,
    admin_members: 20,
    reps_members: 1,
    ra_members: 7,
    students: 107,
    philcare_staff: 4,
    security_personnel: 2,
    construction_workers: 6,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2026-01-22T15:40:00+08:00',
  },
  {
    quarter: 'Q1 2026',
    cluster: 'Pedro Gil',
    unit: 'College of Medicine',
    faculty_members: 49,
    admin_members: 103,
    reps_members: 3,
    ra_members: 7,
    students: 250,
    philcare_staff: 27,
    security_personnel: 9,
    construction_workers: 22,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 2,
    guests: 1,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2026-01-22T15:38:00+08:00',
  },
  {
    quarter: 'Q1 2026',
    cluster: 'Pedro Gil',
    unit: 'National Institutes of Health',
    faculty_members: 0,
    admin_members: 9,
    reps_members: 0,
    ra_members: 0,
    students: 0,
    philcare_staff: 0,
    security_personnel: 0,
    construction_workers: 0,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 1,
    casualties_count: 0,
    timestamp: '2026-01-22T15:35:00+08:00',
  },
  {
    quarter: 'Q1 2026',
    cluster: 'Pedro Gil',
    unit: 'College of Public Health',
    faculty_members: 13,
    admin_members: 31,
    reps_members: 8,
    ra_members: 8,
    students: 59,
    philcare_staff: 8,
    security_personnel: 4,
    construction_workers: 42,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2026-01-22T11:00:00+08:00',
  },
  {
    quarter: 'Q1 2026',
    cluster: 'Padre Faura',
    unit: 'Joaquin Gonzales Building',
    faculty_members: 0,
    admin_members: 3,
    reps_members: 3,
    ra_members: 0,
    students: 0,
    philcare_staff: 1,
    security_personnel: 0,
    construction_workers: 0,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2026-01-22T15:56:00+08:00',
  },
  {
    quarter: 'Q1 2026',
    cluster: 'Padre Faura',
    unit: 'Campus Planning, Development, and Management Office',
    faculty_members: 0,
    admin_members: 26,
    reps_members: 0,
    ra_members: 0,
    students: 0,
    philcare_staff: 1,
    security_personnel: 1,
    construction_workers: 0,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    timestamp: '2026-01-22T15:51:00+08:00',
  },
  {
    quarter: 'Q1 2026',
    cluster: 'Padre Faura',
    unit: 'College of Arts and Sciences',
    faculty_members: 25,
    admin_members: 30,
    reps_members: 2,
    ra_members: 2,
    students: 593,
    philcare_staff: 10,
    security_personnel: 8,
    construction_workers: 25,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 7,
    missing_count: 0,
    casualties_count: 9,
    timestamp: '2026-01-22T15:39:00+08:00',
  },
];

// ─── Main ─────────────────────────────────────────────────
async function main() {
  console.log('Starting seed...\n');

  // ── 1. Lookup tables ────────────────────────────────────
  console.log('Seeding lookup tables...');

  // Clusters
  await prisma.cluster.createMany({
    data: CLUSTERS.map((name) => ({ name, is_active: true })),
    skipDuplicates: true,
  });
  console.log(`  clusters: ${CLUSTERS.length}`);

  // Build cluster name → id map (needed for FK inserts below)
  const clusterRecords = await prisma.cluster.findMany({ select: { id: true, name: true } });
  const clusterMap: Record<string, string> = Object.fromEntries(
    clusterRecords.map((c) => [c.name, c.id])
  );

  // Units
  const unitData = Object.entries(UNITS).flatMap(([clusterName, units]) =>
    units.map((name) => ({ name, cluster_id: clusterMap[clusterName], is_active: true }))
  );
  await prisma.unit.createMany({ data: unitData, skipDuplicates: true });
  console.log(`  units: ${unitData.length}`);

  // Locations
  const locationData = Object.entries(LOCATIONS).flatMap(([clusterName, locations]) =>
    locations.map((name) => ({ name, cluster_id: clusterMap[clusterName], is_active: true }))
  );
  await prisma.location.createMany({ data: locationData, skipDuplicates: true });
  console.log(`  locations: ${locationData.length}`);

  // Casualty Conditions
  await prisma.casualtyCondition.createMany({
    data: CASUALTY_CONDITIONS.map((name) => ({ name, is_active: true })),
    skipDuplicates: true,
  });
  console.log(`  casualty_conditions: ${CASUALTY_CONDITIONS.length}`);

  // Damage Report
  await prisma.damageCondition.createMany({
    data: DAMAGE_CONDITION.map((name) => ({ name, is_active: true })),
    skipDuplicates: true,
  });
  console.log(`  damage_conditions: ${DAMAGE_CONDITION.length}`);

  // Positions
  await prisma.position.createMany({
    data: POSITIONS.map((name) => ({ name, is_active: true })),
    skipDuplicates: true,
  });
  console.log(`  positions: ${POSITIONS.length}`);

  // User Types
  const userTypeNames = Object.values(USER_TYPES);
  await prisma.userType.createMany({
    data: userTypeNames.map((name) => ({ name, is_active: true })),
    skipDuplicates: true,
  });
  console.log(`  user_types: ${userTypeNames.length}`);

  // Event Statuses
  await prisma.eventStatus.createMany({
    data: EVENT_STATUSES.map((name) => ({ name, is_active: true })),
    skipDuplicates: true,
  });
  console.log(`  event_statuses: ${EVENT_STATUSES.length}`);

  // Bystander Incident Types
  await prisma.bystander_incident_types.createMany({
    data: BYSTANDER_INCIDENT_TYPES.map((name) => ({ name, is_active: true })),
    skipDuplicates: true,
  });
  console.log(`  bystander_incident_types: ${BYSTANDER_INCIDENT_TYPES.length}`);

  const statusRecords = await prisma.eventStatus.findMany({ select: { id: true, name: true } });
  const statusMap: Record<string, string> = Object.fromEntries(
    statusRecords.map((s) => [s.name, s.id])
  );

  const unitRecords = await prisma.unit.findMany({
    select: {
      id: true,
      name: true,
      cluster: {
        select: { name: true },
      },
    },
  });
  const unitMap: Record<string, string> = Object.fromEntries(
    unitRecords.map((u) => [`${u.cluster.name}:${u.name}`, u.id])
  );

  // ── 3. Events — one per quarter ─────────────────────────
  console.log('\nSeeding events...');

  const quarters = Object.keys(QUARTER_DATES).sort();
  const eventMap: Record<string, string> = {};

  for (const quarter of quarters) {
    const dates = QUARTER_DATES[quarter];
    const event = await prisma.event.create({
      data: {
        name: `NSED ${quarter}`,
        description: `National Simultaneous Earthquake Drill - ${quarter}`,
        quarter,
        status_id: statusMap['completed'],
        started_at: dates.started_at,
        ended_at: dates.ended_at,
      },
    });
    eventMap[quarter] = event.id;
    console.log(`  ${event.name}`);
  }

  // ── 4. Reports ───────────────────────────────────────────
  console.log('\nSeeding reports...');

  let count = 0;
  for (const r of REPORT_DATA as any[]) {
    const event_id = eventMap[r.quarter];
    if (!event_id) {
      console.warn(`  Skipping — no event for quarter: ${r.quarter}`);
      continue;
    }

    await prisma.report.create({
      data: {
        event_id,
        cluster_id: clusterMap[r.cluster],
        unit_id: unitMap[`${r.cluster}:${r.unit}`] ?? null,
        faculty_members: r.faculty_members,
        admin_members: r.admin_members,
        reps_members: r.reps_members,
        ra_members: r.ra_members,
        students: r.students,
        philcare_staff: r.philcare_staff,
        security_personnel: r.security_personnel,
        construction_workers: r.construction_workers,
        tenants: r.tenants,
        health_workers: r.health_workers,
        non_academic_staff: r.non_academic_staff,
        guests: r.guests,
        submitted_at: new Date(r.timestamp),
      },
    });
    count++;
  }

  console.log(`\nSeed complete!`);
  console.log(`  Events:  ${quarters.length}`);
  console.log(`  Reports: ${count}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
